const wordDatabase = [
    // --- 1 STAR (Very Easy / A1 Entry) ---
    { word: "Cat", tier: "Very Easy", stars: "⭐", baseline: 30 },
    { word: "Dog", tier: "Very Easy", stars: "⭐", baseline: 30 },
    { word: "Sun", tier: "Very Easy", stars: "⭐", baseline: 30 },
    { word: "Hat", tier: "Very Easy", stars: "⭐", baseline: 30 },
    { word: "Cup", tier: "Very Easy", stars: "⭐", baseline: 30 },
    { word: "Pen", tier: "Very Easy", stars: "⭐", baseline: 30 },
    { word: "Book", tier: "Very Easy", stars: "⭐", baseline: 30 },
    { word: "Box", tier: "Very Easy", stars: "⭐", baseline: 30 },
    { word: "Car", tier: "Very Easy", stars: "⭐", baseline: 30 },
    { word: "Bed", tier: "Very Easy", stars: "⭐", baseline: 30 },
    { word: "Ball", tier: "Very Easy", stars: "⭐", baseline: 30 },
    { word: "Door", tier: "Very Easy", stars: "⭐", baseline: 30 },
    { word: "Fish", tier: "Very Easy", stars: "⭐", baseline: 30 },
    { word: "Frog", tier: "Very Easy", stars: "⭐", baseline: 30 },
    { word: "Girl", tier: "Very Easy", stars: "⭐", baseline: 30 },
    { word: "Boy", tier: "Very Easy", stars: "⭐", baseline: 30 },
    { word: "Hand", tier: "Very Easy", stars: "⭐", baseline: 30 },
    { word: "Milk", tier: "Very Easy", stars: "⭐", baseline: 30 },
    { word: "Moon", tier: "Very Easy", stars: "⭐", baseline: 30 },
    { word: "Nest", tier: "Very Easy", stars: "⭐", baseline: 30 },

    // --- 2 STARS (Easy / A1 Advanced) ---
    { word: "Pond", tier: "Easy", stars: "⭐⭐", baseline: 60 },
    { word: "Rain", tier: "Easy", stars: "⭐⭐", baseline: 60 },
    { word: "Ring", tier: "Easy", stars: "⭐⭐", baseline: 60 },
    { word: "Ship", tier: "Easy", stars: "⭐⭐", baseline: 60 },
    { word: "Sock", tier: "Easy", stars: "⭐⭐", baseline: 60 },
    { word: "Star", tier: "Easy", stars: "⭐⭐", baseline: 60 },
    { word: "Tree", tier: "Easy", stars: "⭐⭐", baseline: 60 },
    { word: "Vase", tier: "Easy", stars: "⭐⭐", baseline: 60 },
    { word: "Wind", tier: "Easy", stars: "⭐⭐", baseline: 60 },
    { word: "Apple", tier: "Easy", stars: "⭐⭐", baseline: 60 },
    { word: "Baby", tier: "Easy", stars: "⭐⭐", baseline: 60 },
    { word: "Bird", tier: "Easy", stars: "⭐⭐", baseline: 60 },
    { word: "Boat", tier: "Easy", stars: "⭐⭐", baseline: 60 },
    { word: "Cake", tier: "Easy", stars: "⭐⭐", baseline: 60 },
    { word: "Chair", tier: "Easy", stars: "⭐⭐", baseline: 60 },
    { word: "Duck", tier: "Easy", stars: "⭐⭐", baseline: 60 },
    { word: "Egg", tier: "Easy", stars: "⭐⭐", baseline: 60 },
    { word: "Fan", tier: "Easy", stars: "⭐⭐", baseline: 60 },
    { word: "Fire", tier: "Easy", stars: "⭐⭐", baseline: 60 },
    { word: "Gold", tier: "Easy", stars: "⭐⭐", baseline: 60 },

    // --- 3 STARS (Medium / B1) ---
    { word: "Vacuum", tier: "Medium", stars: "⭐⭐⭐", baseline: 100 },
    { word: "Clock", tier: "Medium", stars: "⭐⭐⭐", baseline: 100 },
    { word: "Stapler", tier: "Medium", stars: "⭐⭐⭐", baseline: 100 },
    { word: "Dragon", tier: "Medium", stars: "⭐⭐⭐", baseline: 100 },
    { word: "Pirate", tier: "Medium", stars: "⭐⭐⭐", baseline: 100 },
    { word: "Vampire", tier: "Medium", stars: "⭐⭐⭐", baseline: 100 },
    { word: "Japan", tier: "Medium", stars: "⭐⭐⭐", baseline: 100 },
    { word: "Guitar", tier: "Medium", stars: "⭐⭐⭐", baseline: 100 },
    { word: "Batman", tier: "Medium", stars: "⭐⭐⭐", baseline: 100 },
    { word: "France", tier: "Medium", stars: "⭐⭐⭐", baseline: 100 },
    { word: "Zombie", tier: "Medium", stars: "⭐⭐⭐", baseline: 100 },
    { word: "Robot", tier: "Medium", stars: "⭐⭐⭐", baseline: 100 },
    { word: "Planet", tier: "Medium", stars: "⭐⭐⭐", baseline: 100 },
    { word: "Camera", tier: "Medium", stars: "⭐⭐⭐", baseline: 100 },
    { word: "Castle", tier: "Medium", stars: "⭐⭐⭐", baseline: 100 },
    { word: "Wizard", tier: "Medium", stars: "⭐⭐⭐", baseline: 100 },
    { word: "Brazil", tier: "Medium", stars: "⭐⭐⭐", baseline: 100 },
    { word: "Spider", tier: "Medium", stars: "⭐⭐⭐", baseline: 100 },
    { word: "Mummy", tier: "Medium", stars: "⭐⭐⭐", baseline: 100 },
    { word: "Tunnel", tier: "Medium", stars: "⭐⭐⭐", baseline: 100 },

    // --- 4 STARS (Hard / B2) ---
    { word: "Helmet", tier: "Hard", stars: "⭐⭐⭐⭐", baseline: 150 },
    { word: "Rocket", tier: "Hard", stars: "⭐⭐⭐⭐", baseline: 150 },
    { word: "Canada", tier: "Hard", stars: "⭐⭐⭐⭐", baseline: 150 },
    { word: "Hammer", tier: "Hard", stars: "⭐⭐⭐⭐", baseline: 150 },
    { word: "Anchor", tier: "Hard", stars: "⭐⭐⭐⭐", baseline: 150 },
    { word: "Magnet", tier: "Hard", stars: "⭐⭐⭐⭐", baseline: 150 },
    { word: "Subway", tier: "Hard", stars: "⭐⭐⭐⭐", baseline: 150 },
    { word: "Bandage", tier: "Hard", stars: "⭐⭐⭐⭐", baseline: 150 },
    { word: "Italy", tier: "Hard", stars: "⭐⭐⭐⭐", baseline: 150 },
    { word: "Pyramid", tier: "Hard", stars: "⭐⭐⭐⭐", baseline: 150 },
    { word: "Volcano", tier: "Hard", stars: "⭐⭐⭐⭐", baseline: 150 },
    { word: "Skeleton", tier: "Hard", stars: "⭐⭐⭐⭐", baseline: 150 },
    { word: "Penguin", tier: "Hard", stars: "⭐⭐⭐⭐", baseline: 150 },
    { word: "Titanic", tier: "Hard", stars: "⭐⭐⭐⭐", baseline: 150 },
    { word: "Avatar", tier: "Hard", stars: "⭐⭐⭐⭐", baseline: 150 },
    { word: "Frozen", tier: "Hard", stars: "⭐⭐⭐⭐", baseline: 150 },
    { word: "Shrek", tier: "Hard", stars: "⭐⭐⭐⭐", baseline: 150 },
    { word: "Matrix", tier: "Hard", stars: "⭐⭐⭐⭐", baseline: 150 },
    { word: "Google", tier: "Hard", stars: "⭐⭐⭐⭐", baseline: 150 },
    { word: "Nike", tier: "Hard", stars: "⭐⭐⭐⭐", baseline: 150 },

    // --- 5 STARS (Expert / C1-C2) ---
    { word: "Photosynthesis", tier: "Expert", stars: "⭐⭐⭐⭐⭐", baseline: 200 },
    { word: "Constellation", tier: "Expert", stars: "⭐⭐⭐⭐⭐", baseline: 200 },
    { word: "Archipelago", tier: "Expert", stars: "⭐⭐⭐⭐⭐", baseline: 200 },
    { word: "Microscope", tier: "Expert", stars: "⭐⭐⭐⭐⭐", baseline: 200 },
    { word: "Amphitheater", tier: "Expert", stars: "⭐⭐⭐⭐⭐", baseline: 200 },
    { word: "Metamorphosis", tier: "Expert", stars: "⭐⭐⭐⭐⭐", baseline: 200 },
    { word: "Exoskeleton", tier: "Expert", stars: "⭐⭐⭐⭐⭐", baseline: 200 },
    { word: "Seismograph", tier: "Expert", stars: "⭐⭐⭐⭐⭐", baseline: 200 },
    { word: "Trigonometry", tier: "Expert", stars: "⭐⭐⭐⭐⭐", baseline: 200 },
    { word: "Cartographer", tier: "Expert", stars: "⭐⭐⭐⭐⭐", baseline: 200 },
    { word: "Hieroglyphics", tier: "Expert", stars: "⭐⭐⭐⭐⭐", baseline: 200 },
    { word: "Chameleon", tier: "Expert", stars: "⭐⭐⭐⭐⭐", baseline: 200 },
    { word: "Bioluminescence", tier: "Expert", stars: "⭐⭐⭐⭐⭐", baseline: 200 },
    { word: "Centrifuge", tier: "Expert", stars: "⭐⭐⭐⭐⭐", baseline: 200 },
    { word: "Stethoscope", tier: "Expert", stars: "⭐⭐⭐⭐⭐", baseline: 200 },
    { word: "Thermodynamics", tier: "Expert", stars: "⭐⭐⭐⭐⭐", baseline: 200 },
    { word: "Paleontologist", tier: "Expert", stars: "⭐⭐⭐⭐⭐", baseline: 200 },
    { word: "Architecture", tier: "Expert", stars: "⭐⭐⭐⭐⭐", baseline: 200 },
    { word: "Electrocardiogram", tier: "Expert", stars: "⭐⭐⭐⭐⭐", baseline: 200 },
    { word: "Observatory", tier: "Expert", stars: "⭐⭐⭐⭐⭐", baseline: 200 }
];

window.wordDatabase = wordDatabase;